package DAO;
// Generated 2/04/2016 02:26:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private String correo;
     private String nombre;
     private String nombreusuario;
     private String password;
     private Set sesions = new HashSet(0);

    public Registro() {
    }

	
    public Registro(String correo) {
        this.correo = correo;
    }
    public Registro(String correo, String nombre, String nombreusuario, String password, Set sesions) {
       this.correo = correo;
       this.nombre = nombre;
       this.nombreusuario = nombreusuario;
       this.password = password;
       this.sesions = sesions;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getSesions() {
        return this.sesions;
    }
    
    public void setSesions(Set sesions) {
        this.sesions = sesions;
    }




}


