package DAO;
// Generated 2/04/2016 02:26:31 PM by Hibernate Tools 4.3.1



/**
 * Sesion generated by hbm2java
 */
public class Sesion  implements java.io.Serializable {


     private String nombreusuario;
     private Registro registro;
     private String password;

    public Sesion() {
    }

	
    public Sesion(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public Sesion(String nombreusuario, Registro registro, String password) {
       this.nombreusuario = nombreusuario;
       this.registro = registro;
       this.password = password;
    }
   
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public Registro getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Registro registro) {
        this.registro = registro;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


